"""Add reservation table

Revision ID: 2468564cec79
Revises: 
Create Date: 2025-08-09 20:03:40.603474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2468564cec79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='Customer phone number in international format'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Customer name'),
    sa.Column('reservation_date', sa.Date(), nullable=False, comment='Date of reservation'),
    sa.Column('reservation_time', sa.Time(), nullable=False, comment='Time of reservation'),
    sa.Column('party_size', sa.Integer(), nullable=False, comment='Number of people in the party'),
    sa.Column('other_info', sa.JSON(), nullable=True, comment='Additional information (dietary restrictions, special requests, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('phone_number')
    )
    op.create_index(op.f('ix_reservations_name'), 'reservations', ['name'], unique=False)
    op.create_index(op.f('ix_reservations_reservation_date'), 'reservations', ['reservation_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_reservation_date'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_name'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
